### ISSUE TITLE
Cannot use current directory for install

### ISSUE THREAD

**Issue by JoanLaRosa** [skeletonlabs/create-skeleton-app#40]
Was trying to `npm create skeleton-app@latest` in an empty folder and got an error:
```
$ npm create skeleton-app@latest
┌  Create Skeleton App (version 0.0.49)

Welcome to Skeleton 💀! A UI toolkit for Svelte + Tailwind

Problems? Open an issue on https://github.com/skeletonlabs/skeleton/issues if none exists already.
│
◇  Where should we install your project (Enter for current directory) ?
│
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at basename (node:path:1312:5)
    at askForMissingParams (file:///home/joan/.npm/_npx/ed0f586322dee443/node_modules/create-skeleton-app/src/index.js:158:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///home/joan/.npm/_npx/ed0f586322dee443/node_modules/create-skeleton-app/src/index.js:44:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.3.0
npm ERR! code 1
npm ERR! path /home/joan/my-new-really-cool-project
npm ERR! command failed
npm ERR! command sh -c create-skeleton-app

npm ERR! A complete log of this run can be found in: /home/joan/.npm/_logs/2023-08-30T02_45_23_140Z-debug-0.log
```
```
$ node --version
v20.3.0
$ npm --version
9.8.1
```

**Comment by JoanLaRosa** [comment]
Edit: Works with "." (dot) instead of empty.
