### ISSUE TITLE
Failed to load PostCSS Config, cannot find moduel ts-node

### ISSUE THREAD

**Issue by lucianchickenlover** [skeletonlabs/create-skeleton-app#45]
Just tried making a new project with the create app, but it wouldn't work. Nothing else besides standard things added.

```npm run dev

> aaa@0.0.1 dev
> vite dev



  VITE v4.4.9  ready in 803 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: C:/Users/avoider/src/aaa): [Error] 'ts-node' is required for the TypeScript configuration files. Make sure it is installed
Error: Cannot find module 'ts-node'
Require stack:
- C:\Users\avoider\src\aaa\node_modules\vite\dist\node\chunks\dep-df561101.js
Error: 'ts-node' is required for the TypeScript configuration files. Make sure it is installed
Error: Cannot find module 'ts-node'
Require stack:
- C:\Users\avoider\src\aaa\node_modules\vite\dist\node\chunks\dep-df561101.js
    at file:///C:/Users/avoider/src/aaa/node_modules/vite/dist/node/chunks/dep-df561101.js:36571:17
    at Object.search (file:///C:/Users/avoider/src/aaa/node_modules/vite/dist/node/chunks/dep-df561101.js:28958:44)]

Node.js v20.5.0```

**Comment by endigo9740** [comment]
Thanks for reporting @lucianchickenlover. I've confirmed the same error on my end. @niktek maintains the CLI, so I'll make sure he's aware and we get this patched up asap.

```
❯ npm create skeleton-app@latest my-skeleton-app
Need to install the following packages:
  create-skeleton-app@0.0.52
Ok to proceed? (y) 
┌  Create Skeleton App (version 0.0.52)
	
Welcome to Skeleton 💀! A UI toolkit for Svelte + Tailwind

Problems? Open an issue on https://github.com/skeletonlabs/skeleton/issues if none exists already.
│
◇  Which Skeleton app template?
│  AppShell starter
│
◇  Select a theme (top most selection will be default):
│  Skeleton
│
◇
What other packages would you like to install:
│  none
│
◇  Add type checking with TypeScript?
│  Yes, using TypeScript syntax
│
◇  What would you like setup in your project:
│  none
│
◇  Done installing

Done! You can now:

cd my-skeleton-app
npm install
npm run dev
Need some help or found an issue? Visit us on Discord https://discord.gg/EXqV7W8MtY
❯ cd my-skeleton-app
❯ pnpm i
Packages: +168
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/chris/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
node_modules/.pnpm/svelte-preprocess@5.0.4_postcss@8.4.30_svelte@4.0.5_typescript@5.2.2/node_modules/svelte-preprocess: Running postinstall script, done in 8ms
node_modules/.pnpm/@sveltejs+kit@1.20.4_svelte@4.0.5_vite@4.4.2/node_modules/@sveltejs/kit: Running postinstall script, done in 566ms
Progress: resolved 189, reused 164, downloaded 4, added 168, done

devDependencies:
+ @skeletonlabs/skeleton 2.2.0
+ @skeletonlabs/tw-plugin 0.2.1
+ @sveltejs/adapter-auto 2.0.0 (2.1.0 is available)
+ @sveltejs/kit 1.20.4 (1.25.1 is available)
+ @types/node 20.7.0
+ autoprefixer 10.4.16
+ postcss 8.4.30
+ svelte 4.0.5 (4.2.1 is available)
+ svelte-check 3.4.3 (3.5.2 is available)
+ tailwindcss 3.3.3
+ tslib 2.4.1 (2.6.2 is available)
+ typescript 5.0.2 (5.2.2 is available)
+ vite 4.4.2 (4.4.9 is available)
+ vite-plugin-tailwind-purgecss 0.1.3

Done in 3.1s
❯ pnpm dev

> my-skeleton-app@0.0.1 dev /Users/chris/Development/testbed/my-skeleton-app
> vite dev
```

```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /Users/chris/Development/testbed/my-skeleton-app): [Error] 'ts-node' is required for the TypeScript configuration files. Make sure it is installed
Error: Cannot find module 'ts-node'
Require stack:
- /Users/chris/Development/testbed/my-skeleton-app/node_modules/.pnpm/vite@4.4.2_@types+node@20.7.0/node_modules/vite/dist/node/chunks/dep-8609dc5d.js
Error: 'ts-node' is required for the TypeScript configuration files. Make sure it is installed
Error: Cannot find module 'ts-node'
Require stack:
- /Users/chris/Development/testbed/my-skeleton-app/node_modules/.pnpm/vite@4.4.2_@types+node@20.7.0/node_modules/vite/dist/node/chunks/dep-8609dc5d.js
    at file:///Users/chris/Development/testbed/my-skeleton-app/node_modules/.pnpm/vite@4.4.2_@types+node@20.7.0/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:36564:17
    at Object.search (file:///Users/chris/Development/testbed/my-skeleton-app/node_modules/.pnpm/vite@4.4.2_@types+node@20.7.0/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28951:44)]

Node.js v20.3.1
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by Water-Enjoyer** [comment]
Also getting this issue, can be avoided by simply using the old version of create-skeleton-app

`npx create-skeleton-app@0.0.51 my-skeleton-app`

**Comment by PenT1x** [comment]
I fixed it by just changing the postcss.config.js to postcss.config.cjs
This is also what it is called in the old one.

**Comment by endigo9740** [comment]
Thank you @PenT1x. Hopefully that'll be a quick fix.

I will say if the issue persists, we do offer a manual install option too. It's a bit more involved obviously, but might be a viable work around for now:
https://www.skeleton.dev/docs/get-started

**Comment by Mahmoud-zino** [comment]
@niktek This issue was already fixed by you ^^ also I tested it again so it is safe to close it 👍
